### ISSUE TITLE
Was this plug-in module compiled for linux anytime?

### ISSUE THREAD

**Issue by iqch** [unity3d-jp/USDForUnity#1]
It is full of MS types and functions, so we have a lot of troubles digging into such procedure. Btw, for windows everything passed without any troubles. It is a nice job you've made widows port for usd/osd libraries, I've had not sufficient patience to make this.

May you check linux compatibility, fix some issues and give us building instructions? We are very interested with USD embedding to Unity, since we have already first iteration of USD-oriented pipeline too, but we are lunux-oriented band.

tls.h contains a mistype with name of pthread.h file

Thank you!

**Comment by i-saint** [comment]
thanks for your interest.
as you noticed, currently this plugin works only on Windows. readme.md is very very outdated. I'll try to fix Linux build and documents.
I'm making this plugin for our client who also is trying USD-oriented pipeline. maybe material is import / export as NVIDIA's MDL.

**Comment by iqch** [comment]
Thank you for answer!
Now we decide to just plug usd-libraries to Mono assemblies, but since it is terra incognita for us (we have good experience with .NET at windows, not linux) - and Unity developement too - so we have a bit panic  state (even we have passed such state with usd itself). Too much new information, few sources of real inspiring achievements :). Yes, we had compiled this module for windows, it works fine with Unity (but not standalone tools :/ - it is strange). May we just take a commit point, wich is last compatible with linux to inspect you approach for this kind of tasks? We need not now very expanded code or explanation - just appropriate startpoint for our researches. We are a small animation & fx production studio, just exploring new ways of effective production.
Thank you.

**Comment by i-saint** [comment]
I fixed Linux build and updated documents (it is still wip). new documents may help your understanding. https://github.com/unity3d-jp/USDForUnity/tree/dev

**Comment by iqch** [comment]
Thank you very much! 
We built module and now we should figure with embedding, but it is perfect point of further departure! We are interrested with NVIDIA's material system too, it is really romising technology. Our render department was excited and cry for it already :).
Thank you very much again.
