### ISSUE TITLE
Alembic animation issue on Android

### ISSUE THREAD

**Issue by PriyashSur** [unity3d-jp/USDForUnity#11]
Hello ,

 I am using the alembic importer unity plugin , I was able to successfully import the animated character on unity animation plays flawlessly on unity but the animation wont play when deployed to android device , any idea what might be the issue ?

**Comment by PriyashSur** [comment]
Why are u closing this?  Is it resolved?  I mean the issue?

**Comment by i-saint** [comment]
1. this is not AlembicImporter project
2. documents state supported platforms
