### ISSUE TITLE
How to export from unity to the new Apple's USDZ file format ?

### ISSUE THREAD

**Issue by Edorne** [unity3d-jp/USDForUnity#24]
Hello
I tried to use your "USDForUnity" to create a .usdz file (the new file format of Apple and Pixar): i used your Export Examples Scenes in Unity 2017.3.1 to create a .usd file. Then, i compressed it in a zip file and replace the extension from '.usdc.zip" to ".usdz". 
Next, i tried to open it with an iphoneX under IOS12 (witch of course open the apple's .usdz files example without any problem !)... and the error message is "Can't open the object" ...
Can you help me ?
Thanks a lot

**Comment by i-saint** [comment]
not supported yet.

**Comment by wisdomware** [comment]
I am looking to convert to USDZ not USDC. Can someone help to implement this feature?
