### ISSUE TITLE
Can't get it working on mac

### ISSUE THREAD

**Issue by jimdebrouwer** [unity3d-jp/USDForUnity#4]
Plugin works fine on windows but on my Macbook running Osx I don't see any mesh in my scene.
No errors or warnings showed up..

**Comment by i-saint** [comment]
at least it is working on my and my colleagues' machines. I need more information. can you send me Editor.log file?

**Comment by jimdebrouwer** [comment]
Nevermind import works fine! My mistake :|

**Comment by i-saint** [comment]
I'm relieved.
