### ISSUE TITLE
Points Renderer is missing

### ISSUE THREAD

**Issue by diftow** [unity3d-jp/USDForUnity#8]
There used to be a way to render points in an ABC cache, now suddenly there isn't.

The cache I'm trying to use in Unity is generated from a Maya particle physics simulation.
It only works in a several month old version of the Alembic Importer, but the older version has bugs that prevent me from adjusting the start time, among other things, so I've tried using several new versions as well as this USD for Unity package, and the points renderer is missing in the latest builds/revisions.

I just need to load either sphere meshes or sprites onto the points so they are rendered, but I'm not a coder, so what can I do?

Skype: DIFTOW
Email: Chris@diftow.com

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicImporter/issues/12
