### ISSUE TITLE
Alembic animation can't get motion blur vector

### ISSUE THREAD

**Issue by johnartune** [unity3d-jp/USDForUnity#9]

**Comment by johnartune** [comment]
Alembic animation importer can get vertex interpolated, But still can't get mesh vertex motion blur vector. Is there any good way to get the motion blur with keijiro PostProcessing [https://github.com/keijiro/PostProcessingDemo](url)

**Comment by i-saint** [comment]
there is no way to do it for now. it requires plugin to compute delta motion, upload it to Mesh and draw it with special shader. I will consider it, but it's unlikely to come soon.

**Comment by johnartune** [comment]
@i-saint Thanks, same like the vertices motion have come from shader transform so that means to have no mesh renderer position transform in screen? Hope for short times.
